# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'sshuo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for sshuo
  pod "ESPullToRefresh"
  pod 'SnapKit', '~> 5.0.0'
  pod 'Kingfisher'
  pod 'RAMAnimatedTabBarController'
  pod 'ReachabilitySwift'
  pod 'SwiftyBeaver'

end
